# Generated by Django 2.0.6 on 2019-03-14 14:23

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('date_created', models.DateTimeField(verbose_name=datetime.datetime(2019, 3, 14, 14, 23, 59, 78017, tzinfo=utc))),
                ('last_update', models.DateTimeField(verbose_name=datetime.datetime(2019, 3, 14, 14, 23, 59, 78043, tzinfo=utc))),
                ('image', models.ImageField(blank=True, null=True, upload_to='Images')),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('make_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Related',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('date_created', models.DateTimeField(verbose_name=datetime.datetime(2019, 3, 14, 14, 23, 59, 78779, tzinfo=utc))),
                ('last_update', models.DateTimeField(blank=True, null=True, verbose_name=datetime.datetime(2019, 3, 14, 14, 23, 59, 78805, tzinfo=utc))),
                ('image', models.ImageField(blank=True, null=True, upload_to='Images')),
                ('key_to_Article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wikipediaApp.Article')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='key_to_User',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wikipediaApp.Author'),
        ),
    ]
