# Generated by Django 2.0.6 on 2019-03-19 15:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikipediaApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 19, 15, 42, 35, 110511)),
        ),
        migrations.AlterField(
            model_name='article',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 19, 15, 42, 35, 110560)),
        ),
        migrations.AlterField(
            model_name='related',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 19, 15, 42, 35, 112255)),
        ),
        migrations.AlterField(
            model_name='related',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 19, 15, 42, 35, 112307)),
        ),
    ]
