# Generated by Django 2.0.6 on 2019-03-14 01:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wikipediaApp', '0002_auto_20190313_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_created',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 3, 14, 1, 38, 29, 636380, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Images'),
        ),
        migrations.AlterField(
            model_name='article',
            name='last_update',
            field=models.DateTimeField(blank=True, null=True, verbose_name=datetime.datetime(2019, 3, 14, 1, 38, 29, 636406, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='related',
            name='date_created',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 3, 14, 1, 38, 29, 637134, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='related',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Images'),
        ),
        migrations.AlterField(
            model_name='related',
            name='last_update',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 3, 14, 1, 38, 29, 637156, tzinfo=utc)),
        ),
    ]
