# Generated by Django 2.0.6 on 2019-03-13 02:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wikipediaApp', '0002_auto_20190312_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, upload_to='Images'),
        ),
        migrations.AddField(
            model_name='related',
            name='image',
            field=models.ImageField(blank=True, upload_to='Images'),
        ),
        migrations.AlterField(
            model_name='article',
            name='date_created',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 3, 13, 2, 13, 14, 111610, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='article',
            name='last_update',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 3, 13, 2, 13, 14, 111635, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='related',
            name='date_created',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 3, 13, 2, 13, 14, 112654, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='related',
            name='last_update',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 3, 13, 2, 13, 14, 112696, tzinfo=utc)),
        ),
    ]
