# Generated by Django 2.1.7 on 2019-03-19 22:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikipediaApp', '0002_auto_20190319_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 19, 22, 57, 56, 584076)),
        ),
        migrations.AlterField(
            model_name='article',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 19, 22, 57, 56, 584076)),
        ),
        migrations.AlterField(
            model_name='related',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 19, 22, 57, 56, 585076)),
        ),
        migrations.AlterField(
            model_name='related',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 19, 22, 57, 56, 585076)),
        ),
    ]
