# Generated by Django 2.0.6 on 2019-03-14 02:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wikipediaApp', '0003_auto_20190314_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_created',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 3, 14, 2, 6, 36, 130827, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='article',
            name='last_update',
            field=models.DateTimeField(blank=True, null=True, verbose_name=datetime.datetime(2019, 3, 14, 2, 6, 36, 130851, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='related',
            name='date_created',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 3, 14, 2, 6, 36, 131593, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='related',
            name='last_update',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 3, 14, 2, 6, 36, 131614, tzinfo=utc)),
        ),
    ]
