# Generated by Django 2.0.6 on 2019-03-14 02:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wikipediaApp', '0004_auto_20190314_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_created',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 3, 14, 2, 29, 33, 633472, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(null=True, upload_to='Images'),
        ),
        migrations.AlterField(
            model_name='article',
            name='last_update',
            field=models.DateTimeField(blank=True, null=True, verbose_name=datetime.datetime(2019, 3, 14, 2, 29, 33, 633497, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='related',
            name='date_created',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 3, 14, 2, 29, 33, 634205, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='related',
            name='image',
            field=models.ImageField(null=True, upload_to='Images'),
        ),
        migrations.AlterField(
            model_name='related',
            name='last_update',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 3, 14, 2, 29, 33, 634226, tzinfo=utc)),
        ),
    ]
