# Generated by Django 2.0.6 on 2019-03-20 13:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikipediaApp', '0004_auto_20190320_0543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 20, 13, 40, 37, 479447)),
        ),
        migrations.AlterField(
            model_name='article',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 20, 13, 40, 37, 479473)),
        ),
        migrations.AlterField(
            model_name='related',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 20, 13, 40, 37, 480190)),
        ),
        migrations.AlterField(
            model_name='related',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 20, 13, 40, 37, 480211)),
        ),
    ]
