# Generated by Django 2.0.6 on 2019-03-13 04:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wikipediaApp', '0004_auto_20190313_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_created',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 3, 13, 4, 13, 31, 850481, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='article',
            name='last_update',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 3, 13, 4, 13, 31, 850515, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='related',
            name='date_created',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 3, 13, 4, 13, 31, 851249, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='related',
            name='last_update',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 3, 13, 4, 13, 31, 851271, tzinfo=utc)),
        ),
    ]
