# Generated by Django 2.0.6 on 2019-03-14 02:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wikipediaApp', '0007_auto_20190314_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_created',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 3, 14, 2, 55, 25, 274338, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Images'),
        ),
        migrations.AlterField(
            model_name='article',
            name='last_update',
            field=models.DateTimeField(blank=True, null=True, verbose_name=datetime.datetime(2019, 3, 14, 2, 55, 25, 274364, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='related',
            name='date_created',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 3, 14, 2, 55, 25, 275100, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='related',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Images'),
        ),
        migrations.AlterField(
            model_name='related',
            name='last_update',
            field=models.DateTimeField(blank=True, null=True, verbose_name=datetime.datetime(2019, 3, 14, 2, 55, 25, 275122, tzinfo=utc)),
        ),
    ]
