# Generated by Django 2.0.6 on 2019-03-13 14:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wikipediaApp', '0007_auto_20190313_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_created',
            field=models.DateTimeField(blank=True, null=True, verbose_name=datetime.datetime(2019, 3, 13, 14, 54, 35, 971983, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='article',
            name='last_update',
            field=models.DateTimeField(blank=True, null=True, verbose_name=datetime.datetime(2019, 3, 13, 14, 54, 35, 972008, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='related',
            name='date_created',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 3, 13, 14, 54, 35, 972715, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='related',
            name='last_update',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 3, 13, 14, 54, 35, 972737, tzinfo=utc)),
        ),
    ]
